<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class EventSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('events')->insert([
            [
                'id' => 1,
                'title' => 'World Singles Congress',
                'type' => '1',
                'section_id' => 3,
                'start_date' => '2024-09-03',
                'end_date' => '2024-09-05',
                'time' => '09:00:00',
                'location' => 'Alta Bohol Resort & Convention Center, Baclayon, Tagbilaran City, Bohol, Philippines',
                'latitude' => '9.634145699999998',
                'longitude' => '123.895317',
                'reg_fee' => '1700.00',
                'description' => '<p>THIS IS THE UNBREAKABLE FAITH AND LOVE OF GOD! 🔥</p><p>Are you still having a last congress syndrome??? Here\'s to recap everything that happened!!! Praise the Unbreakable God 🙏 May we go home with our yes and with the fire to continue His mission!</p>',
                'category' => null,
                'is_open_for_non_community' => 1,
                'is_enable_event_registration' => 1,
                'poster' => '1723773484_bohol.jpg',
                'status' => 'Active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 2,
                'title' => 'Youth Leadership Summit',
                'type' => '2',
                'section_id' => 4,
                'start_date' => '2024-10-10',
                'end_date' => '2024-10-12',
                'time' => '10:00:00',
                'location' => 'Cebu City Sports Complex, Cebu City, Philippines',
                'latitude' => '10.3156992',
                'longitude' => '123.8854366',
                'reg_fee' => '1500.00',
                'description' => '<p>Empowering the next generation of leaders with innovative ideas and unwavering determination!</p>',
                'category' => 'Leadership',
                'is_open_for_non_community' => 1,
                'is_enable_event_registration' => 1,
                'poster' => 'youth_leadership_summit.jpg',
                'status' => 'Active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 3,
                'title' => 'Annual Faith Gathering',
                'type' => '1',
                'section_id' => 2,
                'start_date' => '2024-09-25',
                'end_date' => '2024-09-25',
                'time' => '08:00:00',
                'location' => 'Manila Cathedral, Intramuros, Manila, Philippines',
                'latitude' => '14.5919',
                'longitude' => '120.9735',
                'reg_fee' => '2000.00',
                'description' => '<p>A powerful event celebrating our shared faith and community spirit. Join us for three days of worship and fellowship!</p>',
                'category' => 'Spirituality',
                'is_open_for_non_community' => 0,
                'is_enable_event_registration' => 1,
                'poster' => 'annual_faith_gathering.jpg',
                'status' => 'Active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 4,
                'title' => 'Event Three',
                'type' => '3',
                'section_id' => 5,
                'start_date' => '2024-09-14',
                'end_date' => '2024-09-14',
                'time' => '09:30:00',
                'location' => 'SMX Convention Center, Pasay City, Philippines',
                'latitude' => '14.5377521',
                'longitude' => '120.980315',
                'reg_fee' => '2500.00',
                'description' => '<p>Bringing together the brightest minds in technology to share ideas, insights, and innovations.</p>',
                'category' => 'Technology',
                'is_open_for_non_community' => 1,
                'is_enable_event_registration' => 1,
                'poster' => 'tech_innovators_conference.jpg',
                'status' => 'Active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 5,
                'title' => 'Prayer Forum',
                'type' => '2',
                'section_id' => 6,
                'start_date' => '2024-09-15',
                'end_date' => '2024-09-17',
                'time' => '09:00:00',
                'location' => 'Shangri-La at the Fort, BGC, Taguig City, Philippines',
                'latitude' => '14.5533491',
                'longitude' => '121.0465327',
                'reg_fee' => '3000.00',
                'description' => '<p>Exploring the future of global health initiatives with a focus on sustainability and innovation.</p>',
                'category' => 'Health',
                'is_open_for_non_community' => 1,
                'is_enable_event_registration' => 1,
                'poster' => 'global_health_forum.jpg',
                'status' => 'Active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 6,
                'title' => 'Event Four',
                'type' => '3',
                'section_id' => 3,
                'start_date' => '2024-10-20',
                'end_date' => '2024-10-22',
                'time' => '10:00:00',
                'location' => 'Makati Shangri-La, Makati City, Philippines',
                'latitude' => '14.554729',
                'longitude' => '121.024445',
                'reg_fee' => '5000.00',
                'description' => '<p>The premier event for business leaders and entrepreneurs. Connect, learn, and grow.</p>',
                'category' => 'Business',
                'is_open_for_non_community' => 0,
                'is_enable_event_registration' => 1,
                'poster' => 'business_summit.jpg',
                'status' => 'Active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 7,
                'title' => 'Prayer Festival',
                'type' => '4',
                'section_id' => 3,
                'start_date' => '2024-09-29',
                'end_date' => '2024-09-30',
                'time' => '11:00:00',
                'location' => 'Clark Freeport Zone, Pampanga, Philippines',
                'latitude' => '15.1850711',
                'longitude' => '120.5609978',
                'reg_fee' => '1800.00',
                'description' => '<p>A celebration of creativity through music and arts featuring both local and international artists.</p>',
                'category' => 'Entertainment',
                'is_open_for_non_community' => 1,
                'is_enable_event_registration' => 1,
                'poster' => 'music_arts_festival.jpg',
                'status' => 'Active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        ]);

    }
}
